---
title: "How did my taste in music change?"
author: "Suzanne Mulder"
date: "February/March 2022"
output: html_document
---

# Introduction

The corpus I chose are playlists of my most listened songs from 2016 until 2021. This is because I want to find out how my taste in music has changed over the years. I'm interested to see if for example covid changed what type of music I listened to or if there are obvious developments in my taste in music. The corpus consists of 6 groups, my most listened songs of 2016, 2017, 2018, 2019, 2020 and 2021. I expect to have a bit of Ed Sheeran and songs of Disney movies in all of them, but I expect that I listen to more different types of music over the years and that I might have changed a bit from relatively more calm and sad songs to more energetic and dancable songs, but I'm not sure if these suspicions are true. 

  I listen almost exclusively to music on Spotify, the only times I listen to other music is at my parents house on the jukebox, and that is a lot more old music. So the biggest gap in these lists is probably the lack of relatively older songs, I think these playlists mostly exist of new songs, of the year that the list is from or maybe 2 years around that. What might also be a limitations is my way of listening to music; there is a lot of music I like and listen to somewhere in the year, so my total amount of listened songs and different genres might be quite big, but I have periods where I only listen the same album/playlist/artist. In my yearly lists can be seen that there sometimes is almost a whole album of a certain artist in the group of most listened songs, so that will have a big influence on the list, so the lists might not be totally representative of my taste in music those years. 
  
  A song that is very typical in my corpus is Where we land - Ed Sheeran, a relatively slow, romantic song and from Ed Sheeran, he is one of the artists that is in almost every year. Some more strange songs are for example Concerto or 2 organs in C minor BWV 1060: I. Allegro from Bach, I do listen sometimes to classical music, but not a lot. Another relatively strange song in the lists is Musicology of Prince, it is music that I like, but that is a type of music that's not that well represented in these playlists because I don't listen to that on Spotify a lot. A last outlier I want to name is Hard genoeg from Dan, that is a Dutch Rap song from someone I know, and this is a very different song than I normally listen to, because I don't really listen to rap and not that much to Dutch music, so I think this is much more speechy and sort of 'harsh' music than I normally listen to.
